title: "Library lab"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: false

logo: "/assets/images/logo.png"

footer_content: ""

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/librarieshacked/librarylab"
gh_edit_branch: "master"
gh_edit_view_mode: "tree"

color_scheme: hacked