title: "Library lab"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true

logo: "/assets/images/logo.png"

aux_links:
  "GitHub":
    - "https://github.com/librarieshacked"

footer_content: ""

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/librarieshacked/librarylab"
gh_edit_branch: "master"
gh_edit_view_mode: "tree"

collections:
  libraries-at-home:
    permalink: "/:collection/:path/"
    output: true
  mobile-libraries:
    permalink: "/:collection/:path/"
    output: true
  library-map:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    libraries-at-home:
      name: Libraries at home
    mobile-libraries:
      name: Mobile libraries
    library-map:
      name: Library map