title: "Library lab"
remote_theme: pmarsceill/just-the-docs@v0.3.2
color_scheme: "hacked"
search_enabled: false

logo: "https://www.librarylab.uk/assets/images/logo.png"

footer_content: ""

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/librarieshacked/librarylab"
gh_edit_branch: "master"
gh_edit_view_mode: "tree"
